import Amul from "../assets/Images/Amul.avif";
import Amul2 from "../assets/Images/Amul2.avif";
import potato from "../assets/Images/potato.avif";
import potato2 from "../assets/Images/potato2.avif";
import ginger from "../assets/Images/ginger.avif";
import carrot from "../assets/Images/carrot.avif";
import cucumber from "../assets/Images/cucumber.avif";
import cauliflower from "../assets/Images/cauliflower.avif";
import onion from "../assets/Images/onion.avif";
import tomato from "../assets/Images/tomato.avif";
import shimla from "../assets/Images/shimla.avif";
import papaya from "../assets/Images/papaya.avif";
import cabbage from "../assets/Images/cabbage.avif";
import beas from "../assets/Images/beas.avif";
import banana from "../assets/Images/banana.avif";
import coconut from "../assets/Images/coconut.avif";
import pomegranate from "../assets/Images/pomegranate.avif";
import apple from "../assets/Images/apple.avif";
import orange from "../assets/Images/orange.avif";
import mango from "../assets/Images/mango.avif";
import Lime from "../assets/Images/Lime.avif";
import fish from "../assets/Images/fish.avif";
import chicken from "../assets/Images/chicken.avif";
import mutton from "../assets/Images/mutton.avif";
import bread from "../assets/Images/bread.avif";
import bread2 from "../assets/Images/bread2.avif";
import bread3 from "../assets/Images/bread3.avif";
import strawberry from "../assets/Images/strawberry.webp";
import blueberry from "../assets/Images/blueberry.webp";
import avocado from "../assets/Images/avacado.webp";
import spinach from "../assets/Images/spinach.webp";
import broccoli from "../assets/Images/brocolli.jpg";
import fishh from "../assets/Images/fishh.jpg";
import almond from "../assets/Images/almond.jpg";
import walnut from "../assets/Images/walnut.jpg";
import duck from "../assets/Images/duck.webp";
import eggs from "../assets/Images/eggs.jpg";
import prawn from "../assets/Images/prawn.jpg";
import pista from "../assets/Images/pista.jpg";
import dates from "../assets/Images/dates.webp";
import butter from "../assets/Images/butter.jpg";
import cheese from "../assets/Images/cheese.webp";
import paneer from "../assets/Images/paneer.jpg";
import curd from "../assets/Images/curd.jpg";
import cookies from "../assets/Images/cookies.jpg";
import cake from "../assets/Images/cake.jpg";
const products = [
  {
    id: 1,
    name: "Amul Taaza Toned Fresh Milk",
    category: "Dairy",
    price: 28,
    image: Amul,
    quantity: "500ml",
    unit: 1,
    rating: 4.5,
    reviews: "2.3k",
    imported: false,
    type: "Packaged",
    description:
      "Amul Taaza is fresh toned milk that provides essential nutrients and is ideal for everyday consumption. It undergoes strict quality checks ensuring purity and taste.",
    goodFor: "Good for daily nutrition, strong bones, and immune support.",
    weight: "500ml",
  },
  {
    id: 2,
    name: "Amul Taaza Homogenised Toned Milk",
    category: "Dairy",
    price: 74,
    image: Amul2,
    quantity: "1ltr",
    unit: 1,
    rating: 4.7,
    reviews: "3.8k",
    imported: false,
    type: "Packaged",
    description:
      "Amul Taaza Homogenised Toned Milk offers a smooth and creamy texture. Homogenisation prevents cream separation and makes it perfect for tea and coffee.",
    goodFor: "Ideal for tea, coffee, and daily consumption for balanced nutrition.",
    weight: "1 litre",
  },
  {
    id: 3,
    name: "Chandramukhi Potato - New Crop (Alu)",
    category: "Vegetables",
    price: 31,
    image: potato,
    quantity: "1kg",
    unit: 1,
    rating: 4.4,
    reviews: "1.9k",
    imported: false,
    type: "Fresh",
    description:
      "Fresh Chandramukhi potatoes with perfect firmness and taste. These potatoes are suitable for a variety of dishes, from fries to curries.",
    goodFor: "Great for cooking, frying, and making traditional Indian recipes.",
    weight: "1 kg",
  },
  {
    id: 4,
    name: "Ginger (Adrak)",
    category: "Vegetables",
    price: 25,
    image: ginger,
    quantity: "200gm",
    unit: 1,
    rating: 4.6,
    reviews: "1.2k",
    imported: false,
    type: "Fresh",
    description:
      "Fresh ginger with a strong aroma and flavor. Perfect for cooking and medicinal uses such as aiding digestion and reducing inflammation.",
    goodFor: "Useful in teas, cooking, and traditional remedies.",
    weight: "200 gm",
  },
  {
    id: 5,
    name: "Orange Carrot (Gajor)",
    category: "Vegetables",
    price: 22,
    image: carrot,
    quantity: "500g",
    unit: 1,
    rating: 4.8,
    reviews: "2.1k",
    imported: false,
    type: "Fresh",
    description:
      "Sweet and crunchy orange carrots rich in beta-carotene and vitamins. Great as a snack or ingredient in salads and cooked dishes.",
    goodFor: "Good for eyesight, skin health, and boosting immunity.",
    weight: "500 g",
  },
  {
    id: 6,
    name: "Green Cucumber (Shosha)",
    category: "Vegetables",
    price: 27,
    image: cucumber,
    quantity: "(500-700g)",
    unit: 1,
    rating: 4.5,
    reviews: "1.7k",
    imported: false,
    type: "Fresh",
    description:
      "Fresh and crunchy green cucumbers perfect for salads and hydration. Known for their cooling properties.",
    goodFor: "Hydration, skin health, and digestive benefits.",
    weight: "500-700g",
  },
  {
    id: 7,
    name: "Cauliflower (Phoolkobi)",
    category: "Vegetables",
    price: 33,
    image: cauliflower,
    quantity: "1 piece (300-500 g)",
    unit: 1,
    rating: 4.6,
    reviews: "1.4k",
    imported: false,
    type: "Fresh",
    description:
      "Fresh cauliflower heads, crisp and healthy. Perfect for curries, salads, and low-carb dishes.",
    goodFor: "Low-calorie diets, rich in fiber and antioxidants.",
    weight: "300-500g",
  },
  {
    id: 8,
    name: "Onion (Peyaj)",
    category: "Vegetables",
    price: 36,
    image: onion,
    quantity: "(0.95-1.05) kg",
    unit: 1,
    rating: 4.3,
    reviews: "3.1k",
    imported: false,
    type: "Fresh",
    description:
      "Fresh onions, essential for cooking with a pungent aroma and flavor. Versatile in many dishes.",
    goodFor: "Flavor enhancement, digestive aid, and antioxidants.",
    weight: "950-1050g",
  },
  {
    id: 9,
    name: "Desi Tomato (Tamatar)",
    category: "Vegetables",
    price: 15,
    image: tomato,
    quantity: "500g",
    unit: 1,
    rating: 4.7,
    reviews: "2.6k",
    imported: false,
    type: "Fresh",
    description:
      "Juicy and ripe Desi tomatoes with vibrant red color and rich flavor. Perfect for salads, sauces, and cooking.",
    goodFor: "Rich in vitamins, good for heart health and skin.",
    weight: "500g",
  },
  {
    id: 10,
    name: "Jyoti Potato - New Crop (Alu)",
    category: "Vegetables",
    price: 29,
    image: potato2,
    quantity: "(0.95-1.05) kg",
    unit: 1,
    rating: 4.5,
    reviews: "1.8k",
    imported: false,
    type: "Fresh",
    description:
      "Fresh Jyoti potatoes with smooth texture, ideal for various cooking needs from frying to boiling.",
    goodFor: "Cooking versatility and energy-rich food.",
    weight: "950-1050g",
  },
  {
    id: 11,
    name: "Green Capsicum (Shimla Mircha)",
    category: "Vegetables",
    price: 23,
    image: shimla,
    quantity: "(250-280) g",
    unit: 1,
    rating: 4.6,
    reviews: "1.3k",
    imported: false,
    type: "Fresh",
    description:
      "Crunchy green capsicum rich in vitamins and fiber. Adds color and nutrition to meals.",
    goodFor: "Weight management, vitamin C, and antioxidants.",
    weight: "250-280g",
  },
  {
    id: 12,
    name: "Raw Papaya (Kacha Pepe)",
    category: "Vegetables",
    price: 48,
    image: papaya,
    quantity: "1 piece (400-600 g)",
    unit: 1,
    rating: 4.4,
    reviews: "900",
    imported: false,
    type: "Fresh",
    description:
      "Fresh raw papaya ideal for cooking and digestive health. Used in salads and traditional recipes.",
    goodFor: "Aids digestion, rich in enzymes and vitamins.",
    weight: "400-600g",
  },
  {
    id: 13,
    name: "Cabbage (Bandhakopi)",
    category: "Vegetables",
    price: 17,
    image: cabbage,
    quantity: "1 piece (400-600 g)",
    unit: 1,
    rating: 4.5,
    reviews: "1.1k",
    imported: false,
    type: "Fresh",
    description:
      "Fresh cabbage with crunchy leaves, rich in fiber and vitamins. Suitable for salads and cooking.",
    goodFor: "Digestive health, weight loss, and antioxidant support.",
    weight: "400-600g",
  },
  {
    id: 14,
    name: "French Beans - 250 g (Same)",
    category: "Vegetables",
    price: 24,
    image: beas,
    quantity: "250g",
    unit: 1,
    rating: 4.6,
    reviews: "800",
    imported: false,
    type: "Fresh",
    description:
      "Fresh French beans, tender and crisp. Great for stir-fries and nutritious side dishes.",
    goodFor: "Low calories, high fiber, and vitamins.",
    weight: "250g",
  },
  {
    id: 15,
    name: "Baby Banana (Kola)",
    category: "Fruits",
    price: 32,
    image: banana,
    quantity: "4 pieces",
    unit: 1,
    rating: 4.8,
    reviews: "2.7k",
    imported: false,
    type: "Fresh",
    description:
      "Sweet and soft baby bananas, rich in potassium and energy. Perfect for snacking and desserts.",
    goodFor: "Energy boost, digestion, and heart health.",
    weight: "4 pieces",
  },
  {
    id: 16,
    name: "Brown Coconut (Narkel)",
    category: "Fruits",
    price: 55,
    image: coconut,
    quantity: "1 piece",
    unit: 1,
    rating: 4.7,
    reviews: "1.3k",
    imported: false,
    type: "Fresh",
    description:
      "Fresh brown coconut with sweet water and nutritious flesh. Used in cooking, desserts, and beverages.",
    goodFor: "Hydration, energy, and rich in healthy fats.",
    weight: "1 piece",
  },
  {
    id: 17,
    name: "Pomegranate (Dalim)",
    category: "Fruits",
    price: 80,
    image: pomegranate,
    quantity: "1 piece (500-700 g)",
    unit: 1,
    rating: 4.6,
    reviews: "1.5k",
    imported: false,
    type: "Fresh",
    description:
      "Fresh pomegranate with juicy and antioxidant-rich seeds. Great for heart health and immunity.",
    goodFor: "Antioxidants, immunity booster, and digestion.",
    weight: "500-700g",
  },
  {
    id: 18,
    name: "Apple (Malum)",
    category: "Fruits",
    price: 110,
    image: apple,
    quantity: "1 piece (200-300 g)",
    unit: 1,
    rating: 4.7,
    reviews: "3.2k",
    imported: true,
    type: "Imported Fresh",
    description:
      "Crisp and juicy apples imported for high quality. Rich in fiber and vitamins.",
    goodFor: "Heart health, digestion, and antioxidant benefits.",
    weight: "200-300g",
  },
  {
    id: 19,
    name: "Orange (Sinthappu)",
    category: "Fruits",
    price: 50,
    image: orange,
    quantity: "1 piece (150-200 g)",
    unit: 1,
    rating: 4.7,
    reviews: "2.9k",
    imported: false,
    type: "Fresh",
    description:
      "Sweet and tangy oranges full of vitamin C and refreshing flavor. Great for juice and snacking.",
    goodFor: "Vitamin C, immunity, and skin health.",
    weight: "150-200g",
  },
  {
    id: 20,
    name: "Alphonso Mango (Mango)",
    category: "Fruits",
    price: 200,
    image: mango,
    quantity: "1 piece (250-300 g)",
    unit: 1,
    rating: 4.9,
    reviews: "4.1k",
    imported: true,
    type: "Imported Fresh",
    description:
      "Premium Alphonso mangoes, known as king of mangoes with rich sweetness and aroma.",
    goodFor: "Energy, digestion, and vitamins.",
    weight: "250-300g",
  },
  {
    id: 21,
    name: "Lime (Elumichai)",
    category: "Fruits",
    price: 5,
    image: Lime,
    quantity: "1 piece",
    unit: 1,
    rating: 4.4,
    reviews: "1.2k",
    imported: false,
    type: "Fresh",
    description:
      "Fresh lime with tangy juice and zest used widely in cooking and beverages.",
    goodFor: "Digestion, vitamin C, and flavoring.",
    weight: "1 piece",
  },
  {
    id: 22,
    name: "Fresh Indian Rohu Fish",
    category: "Non-veg",
    price: 350,
    image: fish,
    quantity: "1 kg",
    unit: 1,
    rating: 4.6,
    reviews: "950",
    imported: false,
    type: "Fresh",
    description:
      "Fresh Indian Rohu fish, rich in omega-3 fatty acids. Ideal for traditional fish recipes.",
    goodFor: "Protein, omega-3 fatty acids, and heart health.",
    weight: "1 kg",
  },
  {
    id: 23,
    name: "Fresh Chicken (Country)",
    category: "Non-veg",
    price: 250,
    image: chicken,
    quantity: "1 kg",
    unit: 1,
    rating: 4.8,
    reviews: "2.1k",
    imported: false,
    type: "Fresh",
    description:
      "Fresh country chicken with tender meat, ideal for curries and grilling.",
    goodFor: "Protein, muscle building, and versatile cooking.",
    weight: "1 kg",
  },
  {
    id: 24,
    name: "Fresh Mutton (Local)",
    category: "Non-veg",
    price: 550,
    image: mutton,
    quantity: "1 kg",
    unit: 1,
    rating: 4.7,
    reviews: "1.5k",
    imported: false,
    type: "Fresh",
    description:
      "Fresh local mutton with rich flavor, suitable for traditional meat dishes and special occasions.",
    goodFor: "High protein, rich taste, and energy.",
    weight: "1 kg",
  },
  {
    id: 25,
    name: "Brown Bread (Soft and Fresh)",
    category: "Bakery",
    price: 35,
    image: bread,
    quantity: "400g",
    unit: 1,
    rating: 4.5,
    reviews: "1.1k",
    imported: false,
    type: "Packaged",
    description:
      "Soft and fresh brown bread with whole wheat goodness. Perfect for sandwiches and toasts.",
    goodFor: "High fiber, healthy carbs, and energy.",
    weight: "400g",
  },
  {
    id: 26,
    name: "White Bread (Loaf)",
    category: "Bakery",
    price: 30,
    image: bread2,
    quantity: "400g",
    unit: 1,
    rating: 4.3,
    reviews: "1.3k",
    imported: false,
    type: "Packaged",
    description:
      "Classic white bread loaf with soft texture and mild flavor. Great for all-day sandwiches.",
    goodFor: "Energy, convenience, and comfort food.",
    weight: "400g",
  },
  {
    id: 27,
    name: "Multigrain Bread",
    category: "Bakery",
    price: 45,
    image: bread3,
    quantity: "400g",
    unit: 1,
    rating: 4.7,
    reviews: "1.5k",
    imported: false,
    type: "Packaged",
    description:
      "Healthy multigrain bread loaded with multiple grains and seeds. Great for heart health and fiber.",
    goodFor: "High fiber, vitamins, and sustained energy.",
    weight: "400g",
  },
   {
    id: 28,
    name: "Fresh Strawberries",
    category: "Fruits",
    price: 150,
    image: strawberry,
    quantity: "250g",
    unit: 1,
    rating: 4.8,
    reviews: "1.2k",
    imported: true,
    type: "Imported Fresh",
    description:
      "Juicy and sweet fresh strawberries rich in antioxidants and vitamin C. Perfect for desserts and smoothies.",
    goodFor: "Antioxidants, immunity boost, and skin health.",
    weight: "250g",
  },
  {
    id: 29,
    name: "Fresh Blueberries",
    category: "Fruits",
    price: 180,
    image: blueberry,
    quantity: "150g",
    unit: 1,
    rating: 4.9,
    reviews: "900",
    imported: true,
    type: "Imported Fresh",
    description:
      "Fresh blueberries packed with vitamins and antioxidants. Great for snacking and healthy baking.",
    goodFor: "Brain health, antioxidants, and anti-inflammatory benefits.",
    weight: "150g",
  },
  {
    id: 30,
    name: "Avocado (Persea Americana)",
    category: "Fruits",
    price: 120,
    image: avocado,
    quantity: "1 piece (200-250g)",
    unit: 1,
    rating: 4.7,
    reviews: "1.1k",
    imported: false,
    type: "Fresh",
    description:
      "Creamy and nutritious avocado rich in healthy fats and fiber. Ideal for salads, toasts, and smoothies.",
    goodFor: "Heart health, good fats, and weight management.",
    weight: "200-250g",
  },
  {
    id: 31,
    name: "Fresh Spinach (Palak)",
    category: "Vegetables",
    price: 30,
    image: spinach,
    quantity: "200g",
    unit: 1,
    rating: 4.6,
    reviews: "1.4k",
    imported: false,
    type: "Fresh",
    description:
      "Fresh green spinach leaves, rich in iron and vitamins. Perfect for cooking or raw salads.",
    goodFor: "Iron, vitamins, and antioxidant properties.",
    weight: "200g",
  },
  {
    id: 32,
    name: "Fresh Broccoli",
    category: "Vegetables",
    price: 70,
    image: broccoli,
    quantity: "1 piece (300-400g)",
    unit: 1,
    rating: 4.5,
    reviews: "1.0k",
    imported: false,
    type: "Fresh",
    description:
      "Crunchy fresh broccoli heads rich in fiber and vitamins. Great for steaming, stir-fries, and salads.",
    goodFor: "Fiber, antioxidants, and immune support.",
    weight: "300-400g",
  },
  {
    id: 33,
    name: "Raw Almonds",
    category: "Nuts",
    price: 350,
    image: almond,
    quantity: "250g",
    unit: 1,
    rating: 4.7,
    reviews: "1.6k",
    imported: true,
    type: "Packaged",
    description:
      "Crunchy raw almonds rich in vitamin E and healthy fats. Perfect for snacking and baking.",
    goodFor: "Heart health, brain function, and skin.",
    weight: "250g",
  },
  {
    id: 34,
    name: "Raw Walnuts",
    category: "Nuts",
    price: 400,
    image: walnut,
    quantity: "250g",
    unit: 1,
    rating: 4.6,
    reviews: "1.2k",
    imported: true,
    type: "Packaged",
    description:
      "Fresh raw walnuts rich in omega-3 and antioxidants. Great for heart and brain health.",
    goodFor: "Omega-3, antioxidants, and inflammation reduction.",
    weight: "250g",
  },
  {
  id: 35,
  name: "Fresh King Fish",
  category: "Non-veg",
  price: 420,
  image: fishh,
  quantity: "1 kg",
  unit: 1,
  rating: 4.7,
  reviews: "1.1k",
  imported: false,
  type: "Fresh",
  description:
    "Fresh King fish known for its firm texture and rich flavor. Ideal for grilling and frying.",
  goodFor: "High protein, omega-3 fatty acids, and heart health.",
  weight: "1 kg",
},
{
  id: 36,
  name: "Fresh Duck Meat",
  category: "Non-veg",
  price: 480,
  image: duck,
  quantity: "1 kg",
  unit: 1,
  rating: 4.5,
  reviews: "700",
  imported: false,
  type: "Fresh",
  description:
    "Fresh duck meat with rich flavor, suitable for roasting and special recipes.",
  goodFor: "High protein, iron, and rich taste.",
  weight: "1 kg",
},
{
  id: 37,
  name: "Fresh Prawns (Medium Size)",
  category: "Non-veg",
  price: 600,
  image: prawn,
  quantity: "500 gm",
  unit: 1,
  rating: 4.8,
  reviews: "1.3k",
  imported: false,
  type: "Fresh",
  description:
    "Medium-sized fresh prawns perfect for curries, grills, and stir-fries.",
  goodFor: "Protein, low fat, and rich in omega-3 fatty acids.",
  weight: "500 gm",
},
{
  id: 38,
  name: "Eggs (Farm Fresh)",
  category: "Non-veg",
  price: 90,
  image: eggs,
  quantity: "12 pieces",
  unit: 1,
  rating: 4.6,
  reviews: "2.2k",
  imported: false,
  type: "Fresh",
  description:
    "Farm fresh eggs rich in protein and essential nutrients. Ideal for all cooking needs.",
  goodFor: "Muscle building, brain health, and energy.",
  weight: "12 pieces",
},
{
  id: 39,
  name: "Fresh Crab Meat",
  category: "Non-veg",
  price: 750,
  image: fish,
  quantity: "1 kg",
  unit: 1,
  rating: 4.7,
  reviews: "800",
  imported: false,
  type: "Fresh",
  description:
    "Fresh crab meat with sweet taste and delicate texture. Great for seafood delicacies.",
  goodFor: "Protein, low fat, and omega-3 fatty acids.",
  weight: "1 kg",
},
{
  id: 40,
  name: "Pistachios",
  category: "Nuts",
  price: 650,
  image: pista, // import pistachios image
  quantity: "500 g",
  unit: 1,
  rating: 4.8,
  reviews: "1000",
  imported: true,
  type: "Dry Roasted",
  description:
    "Crunchy and flavorful pistachios, rich in antioxidants and healthy fats.",
  goodFor: "Heart health, protein, and fiber.",
  weight: "500 g",
},
{
  id: 41,
  name: "Dates",
  category: "Nuts",
  price: 450,
  image: dates, // import dates image
  quantity: "1 kg",
  unit: 1,
  rating: 4.7,
  reviews: "850",
  imported: false,
  type: "Natural",
  description:
    "Sweet and chewy dates, great as a natural energy booster and fiber source.",
  goodFor: "Energy, digestion, and vitamins.",
  weight: "1 kg",
},
{
  id: 42,
  name: "Amul Butter",
  category: "dairy",
  price: 55,
  image: butter, // import butter image
  quantity: "100 g",
  unit: 1,
  rating: 4.8,
  reviews: "2200",
  imported: false,
  type: "Salted",
  description:
    "Creamy and rich Amul butter perfect for spreading, cooking, and baking.",
  goodFor: "Fats and energy.",
  weight: "100 g",
},
{
  id: 43,
  name: "Cheddar Cheese",
  category: "dairy",
  price: 320,
  image: cheese, // import cheese image
  quantity: "500 g",
  unit: 1,
  rating: 4.6,
  reviews: "900",
  imported: true,
  type: "Processed",
  description:
    "Sharp and tangy cheddar cheese, excellent for sandwiches and pastas.",
  goodFor: "Calcium, protein, and taste.",
  weight: "500 g",
},
{
  id: 44,
  name: "Fresh Curd",
  category: "dairy",
  price: 45,
  image: curd, // import curd image
  quantity: "500 g",
  unit: 1,
  rating: 4.5,
  reviews: "700",
  imported: false,
  type: "Natural",
  description:
    "Thick and creamy homemade-style curd rich in probiotics.",
  goodFor: "Digestion, calcium, and gut health.",
  weight: "500 g",
},
{
  id: 45,
  name: "Paneer",
  category: "dairy",
  price: 280,
  image: paneer, // import paneer image
  quantity: "500 g",
  unit: 1,
  rating: 4.8,
  reviews: "1100",
  imported: false,
  type: "Fresh",
  description:
    "Soft and fresh paneer ideal for curries, snacks, and grilling.",
  goodFor: "Protein, calcium, and vegetarians.",
  weight: "500 g",
},
{
  id: 46,
  name: "Chocolate Chip Cookies",
  category: "Bakery",
  price: 70,
  image: cookies,
  quantity: "6 pieces",
  unit: 1,
  rating: 4.9,
  reviews: "2.1k",
  imported: false,
  type: "Packaged",
  description:
    "Crunchy on the outside, chewy on the inside—these cookies are loaded with chocolate chips.",
  goodFor: "Sweet cravings, snacking, and gifting.",
  weight: "250g",
},
{
  id: 47,
  name: "Banana Walnut Muffins",
  category: "Bakery",
  price: 55,
  image: cake,
  quantity: "2 pieces",
  unit: 1,
  rating: 4.6,
  reviews: "1.2k",
  imported: false,
  type: "Packaged",
  description:
    "Moist and rich muffins made with real bananas and crunchy walnuts. Baked fresh daily.",
  goodFor: "Quick breakfast, snack, and energy boost.",
  weight: "180g",
},

];

export default products;
